In [7]:
import pandas as pd

NPP_df = pd.read_csv('4more4nana.csv')
NPP_df

,Date_created,Tweet,Source
0,2020-11-23 18:26:50,The Pwalugu Multipurpose Dam when completed; w...,Twitter for iPhone
1,2020-11-23 18:22:47,RT @JoJo_Steven1: Year of Roads \n\nRehabilita...,Twitter for iPhone
2,2020-11-23 18:22:17,RT @DwiftEminem: @Thanos_thana @JoJo_Steven1 4...,Twitter for Android
3,2020-11-23 18:16:27,So 4More4Nana ? https://t.co/v3TLXZpsBc,Twitter for iPhone
4,2020-11-23 18:11:28,RT @kofi_badboy: Why #4More4Nana ????\n\n#1Tou...,Twitter Web App
...,...,...,...
2741,2020-11-14 16:34:07,#4More4Nana for Ekumfi juice alone,Twitter for iPhone
2742,2020-11-14 16:34:03,RT @lordcudjoe: Charley..Who else slept in 'du...,Twitter for iPhone
2743,2020-11-14 16:29:51,@pyboamah #4more4Nana,Twitter for Android
2744,2020-11-14 16:21:42,RT @kotokoChyna: #4More4Nana \n#4moreForNYA \n...,Twitter for Android
2745,2020-11-14 16:01:37,#4more4Nana https://t.co/4vEWqhwdnx,Twitter for Android

In [6]:
import pandas as pd

NDC_df = pd.read_csv('JMandJane2020.csv')
NDC_df

,Date_created,Tweet,Source
0,2020-11-23 18:53:21,@NAkufoAddo 4more4nana ðŸ”¥,Twitter for iPhone
1,2020-11-23 18:52:52,@OfficialNDCGh Hahaha ðŸ˜‚ still 4more4nana ðŸ”¥,Twitter for iPhone
2,2020-11-23 18:52:27,Emergency medical deliveries through drones (t...,Twitter for Android
3,2020-11-23 18:41:41,@DBLACKGH 4more4Nana,Twitter for Android
4,2020-11-23 18:41:24,@KALYJAY_BA @NAkufoAddo 4more4nana,Twitter for Android
...,...,...,...
2698,2020-11-14 16:34:07,#4More4Nana for Ekumfi juice alone,Twitter for iPhone
2699,2020-11-14 16:34:03,RT @lordcudjoe: Charley..Who else slept in 'du...,Twitter for iPhone
2700,2020-11-14 16:29:51,@pyboamah #4more4Nana,Twitter for Android
2701,2020-11-14 16:21:42,RT @kotokoChyna: #4More4Nana \n#4moreForNYA \n...,Twitter for Android
2702,2020-11-14 16:01:37,#4more4Nana https://t.co/4vEWqhwdnx,Twitter for Android